name: Code Quality

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci.yml'
      - 'src/**.[ch]'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CMAKE_BUILD_TYPE: Release
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - uses: hustcer/setup-nu@v3
      with:
        version: '0.97.1'
    - name: Check Format
      shell: nu {0}
      run: clang-format --dry-run ...(glob 'src/**/*.{c,h}')
    - name: Configure CMake
      run: cmake --preset=default .
    - name: Check Lints
      shell: nu {0}
      run: clang-tidy --quiet -p .build ...(glob 'src/**/*.{c,h}')
    - name: Build with Make
      run: cmake --build .build
    - name: Run Unit Tests
      run: ctest --preset=default
